# Generated by Django 3.2.9 on 2022-01-29 08:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(choices=[('Pait', 'Pait'), ('Roberts', 'Roberts')], default='Pait', max_length=30)),
                ('course', models.CharField(choices=[('M1/2', 'Math 1/2'), ('M2/3', 'Math 2/3')], default='M2/3', max_length=10)),
                ('streak', models.PositiveSmallIntegerField(default=1)),
                ('reference_date', models.DateField(default=datetime.date.today)),
                ('login_count', models.PositiveSmallIntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
