# Generated by Django 3.2.9 on 2022-01-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M12_Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
                ('topic_date', models.DateField(verbose_name='date taught')),
                ('topic_img', models.ImageField(upload_to='')),
                ('topic_key', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='M23_Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
                ('topic_date', models.DateField(verbose_name='date taught')),
                ('topic_img', models.ImageField(upload_to='')),
                ('topic_key', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
